### ISSUE TITLE
Why big-endian?

### ISSUE THREAD

**Issue by cgbur** [mccullocht/prefix_varint#12]
Since most arch's this will run in will be little endian, is there a reason this is big endian. Could the speed be faster if it was in little endian since you would not need to be swapping bytes?

**Comment by mccullocht** [comment]
Intuitively it should be faster to use a little endian order because x86 and most commercial ARM processors use it (probably for ease of porting from x86!). I think I tried this and it didn't make much of a difference on my host, but I also didn't save the results or maintain a branch so I don't have much to share.

The reasons for this choice were partially aesthetic: it makes sense for the remainder in the prefix coded byte to contain the high bits of the value. In a scheme where any remaining bytes are little endian you end up needing to mask/shift/or to combine the values instead of bswap/(maybe shift)/mask.
